### ISSUE TITLE
How to debug ExecJS::RuntimeError: SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by krzysztofg-ion** [rails/execjs#122]
Hi,
I want run rails application in docker for local development. Application works on MacOs, and on a heroku, but I cannot setup it in container. 
When I try compile assets (`bundle exec rails assets:precompile`) I get this error:
```
ExecJS::RuntimeError: SyntaxError: Invalid or unexpected token
(execjs):706:1
(execjs):724:14
(execjs):1:40
Object.<anonymous> ((execjs):1:58)
Module._compile (internal/modules/cjs/loader.js:999:30)
Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
Module.load (internal/modules/cjs/loader.js:863:32)
Function.Module._load (internal/modules/cjs/loader.js:708:14)
Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
internal/main/run_main_module.js:17:47
/gems/ruby/2.7.0/gems/execjs-2.8.1/lib/execjs/external_runtime.rb:39:in 'exec' 
```
How I can find out what is wrong in my setup?

docker based on `FROM ruby:2.7.5`

```
About your application's environment
Rails version             5.2.6
Ruby version              2.7.5-p203 (x86_64-linux)
RubyGems version          3.1.6
Rack version              2.2.3
JavaScript Runtime        Node.js (V8)
```

In gems I have `therubyracer`

**Comment by ahorek** [comment]
therubyracer is unmaintained and no longer supported by this gem

you can lock it to the older version
```
gem 'exec_js', '2.7.0'
```

or better, update your dependencies
therubyracer -> https://github.com/rubyjs/mini_racer
nodejs https://nodejs.org/en/download/current/ is also an alternative, but you probably have an ancient version, that's why you're getting this error
uglifier -> https://github.com/ahorek/terser-ruby
