### ISSUE TITLE
Syntax error with new HEREDOC syntax

### ISSUE THREAD

**Issue by ramonvic** [rails/execjs#128]
I trying to run new 2.9.0 version in a old ruby version ( 2.1.6 ) but the new HEREDOC `<<~` is not compatible with that version. Has nay reason to use? since execjs has not constraints to be used on that version.
Current Stacktrace:
`SyntaxError: ~/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/execjs-2.9.0/lib/execjs/external_runtime.rb:106: syntax error, unexpected ',', expecting keyword_end
        instance_eval <<~RUBY, __FILE__, __LINE__`

**Comment by byroot** [comment]
I'll add the version constraint for the next release.

**Comment by ramonvic** [comment]
But is there any need for this constraint? I didn't see anything, except what I mentioned, that it was necessary to have `ruby > 2.3`. for old projects, we would lose the possibility of updating the gem.

**Comment by byroot** [comment]
> But is there any need for this constraint?

Yes. If we can't run CI on such old version, then it becomes impossible to prevent changes such as this one to go through.

As you can see only 2.5+ is tested because testing older versions would require jumping through tons of hoops (e.g. get `mini_racer` to compile, etc).


> I didn't see anything, except what I mentioned

There is also keyword arguments: https://github.com/casperisfine/execjs/actions/runs/6172058727/job/16751545205#step:7:22

And here you can see how much we'd have to workaround: https://github.com/rails/execjs/compare/master...casperisfine:execjs:test-1.9.3

I'm always happy to support EOL ruby versions as long as it's not a big hassle, here it is one.
