### ISSUE TITLE
ES5 Features, ES6 and beyond

### ISSUE THREAD

**Issue by nsuchy** [rails/execjs#83]
The README file states the following about ES5 Support:
```
Why can't I use ES5 features?

Some runtimes like Node will implement many of the latest ES5 features. However older stock runtimes like JSC on OSX and JScript on Windows may not. You should only count on ES3 features being available. Prefer feature checking these APIs rather than hard coding support for specific runtimes.
```

README.md has not been updated in 2 years. What, if anything, about this support has changed? How is ES6, ES2015, ES2016, ES2017, and beyond affected (is there any support at all for the new syntax and features). This information would be useful to include in the README.

**Comment by rafaelfranca** [comment]
The situation is the same `Some runtimes like Node will implement many of the latest ES features. However older stock runtimes like JSC on OSX and JScript on Windows may not. You should only count on ES3 features being available. Prefer feature checking these APIs rather than hard coding support for specific runtimes.`

So the README is still correct. Please note that it is talking about writing scripts to be executed using execjs and that needs to support most of the runtimes. If you are using only a runtime that supports ES2017, you should be able to use it.
